services:
  db:
    image: mysql:8.0
    container_name: zzazo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD}
      MYSQL_DATABASE: mydatabase
    ## cmd 내 한글 인코딩 용 명령어 주입
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --skip-character-set-client-handshake
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD","mysqladmin", "ping", "-h" ,"127.0.0.1", "-u", "root" ,"-p${MY_SQL_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    image: nanajun/zzazo:latest
    container_name: my-spring
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_PASSWORD: ${MY_SQL_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_PROFILES_ACTIVE: dev
    restart: always

volumes:
  mysql_data: