name: "[CD] 개발 서버 자동/수동 배포"

on:
  # 'ci-dev.yml' 워크플로우가 main 브랜치에서 성공적으로 끝났을 때 작동
  workflow_run:
    workflows: [ "[CI] 빌드 및 도커 이미지 푸시" ]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    # 앞선 CI가 성공했을 때나, 수동 버튼(workflow_dispatch)을 눌렀을 때만 실행
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: 배포 설정 파일(compose) 전송을 위한 체크아웃
        uses: actions/checkout@v4

      - name: 배포 파일 서버로 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "docker-compose-dev.yml"
          target: "/home/${{ secrets.SERVER_USER }}/zzazo"
          overwrite: true

      - name: 배포 서버 접속 및 도커 컨테이너 재시작 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.SERVER_USER }}/zzazo
            
            # GitHub Secrets에 있는 환경 변수로 배포 환경변수 파일 동적 생성
            echo "${{ secrets.DEV_ENV_FILE }}" > .env
            
            # 최신 도커 이미지 당겨오고 컨테이너 무중단 교체
            sudo docker compose -f docker-compose-dev.yml pull
            sudo docker compose -f docker-compose-dev.yml down --remove-orphans
            sudo docker compose -f docker-compose-dev.yml up -d
            
            # 안 쓰는 이전 구버전 이미지 삭제 (디스크 관리)
            sudo docker image prune -f